### ISSUE TITLE
Use a configuration file for the backup script

### ISSUE THREAD

**Issue by paraenggu** [radiorabe/backup#2]
Create and use a configuration file (a simple shell script which will be sourced by the main script) and add the following settings:
- Path to external commands (including `rsync`)
- Temporary directory (which defaults to `/tmp`)
- Rsync options (with sane default values), so that one can tweak them if needed
- Backup server host name or IP address
- Path to the SSH private key
- Verbosity level
- other additional stuff

expect (source) the configuration relative to the main script (`../etc/rsync-backup/rsync-backup.conf` for example)

**Comment by micressor** [comment]
Done in 939c5320ac8054e6c4c5b23205c829920ceb5a8c
