### ISSUE TITLE
backup-fs-vms.sh: Exlcude and include directories

### ISSUE THREAD

**Issue by paraenggu** [radiorabe/backup#3]
Reorganise the repository directory structure after #2 has been accepted, to the following layout:
- `sbin/rsync-backup.sh`
- `etc/rsync-backup/rsync-backup.conf`
- `etc/rsync-backup/rsync-backup.include`
- `etc/rsync-backup/rsync-backup.exclude`

This allows one to simply checkout the repository and use the scripts, install the scripts directly below `/usr/local` or properly package them without having to modify the paths.

**Comment by micressor** [comment]
What is better? To use a `EXCLUDE=/dir1 /dir2` var or a separate file `rabe-fs-backup.exclude` file with per line directories?

**Comment by paraenggu** [comment]
I would prefer to have separate configuration files for configuring include and exclude paths/patterns. This makes it easier to manage/read than having the whole list on one line as a parameter value. One can also add new paths simply by  concatenating them to a file, rather than having to edit a configuration file. Maybe you can directly use one or more of rsync's `--files-from=FILE`, `--include-from=FILE` and `--exclude-from=FILE` options...

**Comment by spameier** [comment]
I'll do an implementation where the VMs can locally specify `/etc/rabe-backup.{include,exclude}` which the script reads and then does some additional `rsync` calls.
