### ISSUE TITLE
Don't hard-code the exclude filter

### ISSUE THREAD

**Issue by paraenggu** [radiorabe/backup#4]
Remove the hard-coded -`-exclude="profiles/*"`option from [backup.sh:195](https://github.com/radiorabe/backup/blob/5674e5b8a2180e7cb346b4b0dce0b1ecb90d7153/backup.sh#L195) and make it configurable (via #2).

**Comment by micressor** [comment]
:-) I forgot to write, that the script does not work at the moment. It's wild and very beta.

**Comment by micressor** [comment]
done.
