### ISSUE TITLE
Create pre- and post-hooks

### ISSUE THREAD

**Issue by paraenggu** [radiorabe/backup#9]
Create the ability to run custom pre- and post-hook scripts. This is useful for various tasks, such as running a database dump, inform a monitoring system, create and remove filesystem snapshots (#7) etc.

Implementation proposal:

Create three directories:
- `share/rsync-backup/` (directory holding all pre-installed available hook scripts)
- `libexec/rsync-backup/pre-hooks.d` (directory holding symlinks to active pre-hook scripts)
- `libexec/rsync-backup/post-hooks.d` (directory holding symlinks to active post-hook scripts)

This way, an administrator can decide which scripts to enable and use the same script for pre or post hook actions, if applicable.

Run the hooks from the main backup script:
1. Before the rsync run, execute all scripts within `libexec/rsync-backup/pre-hooks.d/*` and pass `pre` as the first argument.
2. After the rsync run, execute all scripts within `libexec/rsync-backup/post-hooks.d/*`, pass `post` as the first and the exit code of rsync as the second argument (this way a post script can react differently on successful or unsuccessful backup runs)

**Comment by hairmare** [comment]
Are we building an app or writing a quick wrapper for rsync? I feel this enhancement brings this whole thing to a stage where bash is possibly not be the best suited language to achieve this.

**Comment by paraenggu** [comment]
The hook dispatcher is pretty easy to implement in bash, the actual hook scripts/executables can be written in any language you like.

**Comment by hairmare** [comment]
It's not about ease of implementation in bash, It's about testability :(

**Comment by paraenggu** [comment]
Well, the script was already implemented in bash ;-)

It would be more helpful, if you could provide an alternative implementation proposal in case you're not happy with the current one, rather than criticising it without bringing up a solution on how to coordinate those backup companion tasks.

**Comment by hairmare** [comment]
I assume that all of this can already be done with systemd.

**Comment by micressor** [comment]
Keep in mind, it should be a one shot wrapper (cron or systemd.timer) script , that gets most of necessary configuration stuff from the current running system.

**Comment by micressor** [comment]
May be it is possible to implement hooks via systemd, instead of script hooks?

**Comment by hairmare** [comment]
Wouldn't `ExecStartPre` and `ExecStartPost` do if this is a `oneshot`? I'm not sure about timers.

**Comment by paraenggu** [comment]
Sounds good to me: Quoting systemd's documentation regarding [ExecStartPre=, ExecStartPost=](https://www.freedesktop.org/software/systemd/man/systemd.service.html#ExecStartPre=):

> Additional commands that are executed before or after the command in ExecStart=, respectively. Syntax is the same as for ExecStart=, except that multiple command lines are allowed and the commands are executed one after the other, serially.
> If any of those commands (not prefixed with "-") fail, the rest are not executed and the unit is considered failed.

**Comment by hairmare** [comment]
I think this can be closed. With [config/rabe-fs-backup.service](https://github.com/radiorabe/backup/blob/5222f51fd2d40d7ab8bcdcc36663c5891bc40301/config/rabe-fs-backup.service) we have a proper service and the docs show [how to add an override](https://github.com/radiorabe/backup/tree/5222f51fd2d40d7ab8bcdcc36663c5891bc40301#systemd-timer).
